#!/bin/sh
HOTSPOT_ENABLED=$(jq -r '.hotspot_enabled' /data/options.json)
if [ "${HOTSPOT_ENABLED}" != "true" ]; then
    echo "[INFO] dnsmasq: disabled"
    exec sleep infinity
fi
echo "[INFO] Starting dnsmasq"
exec dnsmasq --no-daemon -C /tmp/spiderbridge/dnsmasq.conf
