#!/bin/sh
HOTSPOT_ENABLED=$(jq -r '.hotspot_enabled' /data/options.json)
if [ "${HOTSPOT_ENABLED}" != "true" ]; then
    echo "[INFO] hostapd: disabled"
    exec sleep infinity
fi
echo "[INFO] Starting hostapd"
exec hostapd /tmp/spiderbridge/hostapd.conf
